// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BeforeClose(arg1) {
  return window['go']['backend']['App']['BeforeClose'](arg1);
}

export function FrontendInited() {
  return window['go']['backend']['App']['FrontendInited']();
}

export function GetCFG() {
  return window['go']['backend']['App']['GetCFG']();
}

export function GetConfigPath(arg1) {
  return window['go']['backend']['App']['GetConfigPath'](arg1);
}

export function ParseShareCode(arg1) {
  return window['go']['backend']['App']['ParseShareCode'](arg1);
}

export function SetCFG(arg1) {
  return window['go']['backend']['App']['SetCFG'](arg1);
}
