// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {config} from '../models';

export function BeforeClose(arg1:context.Context):Promise<boolean>;

export function FrontendInited():void;

export function GetCFG():Promise<config.CFG>;

export function GetConfigPath(arg1:string):Promise<string>;

export function ParseShareCode(arg1:string):void;

export function SetCFG(arg1:config.CFG):void;
